### ISSUE TITLE
Tidy up build process

### ISSUE THREAD

**Issue by kenhys** [fluent-plugins-nursery/td-agent-builder#207]
# Problem

There is some pile of fixes to build correctly, but it may be stack needless fix too.

# Expected

Clean up needless fixes.

* [x] Remove deprecated `GemParser` #209
* [x] Adding more windows test cases #212
* [x] Remove needless `--priviliged` #210
* [x] Suppress Travis-CI #204 
* [x] Document specinfra patch #215
* [x] Check .conf when package was removed. (deb, rpm) #217
* ~Stop to create c:/var strictly (timing issue?)~
* [x] Do not show command prompt on Windows. #218
* [x] Use meaningful -name in .yml (GitHub Actions) #216
* [x] Check recent lintian/rpmlint #219 #220

**Comment by kenhys** [comment]
needless --auto-commit?

**Comment by kenhys** [comment]
I've forgot to mention specinfra.

**Comment by kenhys** [comment]
check .conf when package was removed. (deb, rpm)

**Comment by kenhys** [comment]
suppress to create c:/var strictly.

**Comment by kenhys** [comment]
do not show command prompt on Windows.

**Comment by kenhys** [comment]
check recent lintian warning again.

**Comment by kenhys** [comment]
Use meaningful `-name` in .yml

**Comment by kenhys** [comment]
#216 was merged.

**Comment by kenhys** [comment]
#217 was merged.

**Comment by kenhys** [comment]
#218 was merged.

**Comment by kenhys** [comment]
#220 was merged, I'll close it.
